### ISSUE TITLE
Next week's plans vanished after submitting

### ISSUE THREAD

**Issue by KunalKorgaonkar** [NVSL/smithers#16]

**Comment by KunalKorgaonkar** [comment]
This happened around 1:50 AM 2nd March when I first submitted. 
It should some error initially so I resubmitted.

**Comment by stevenjswanson** [comment]
If it happens again, please record the error.  

I can't reproduce the error and there's nothing in the logs.

**Comment by stevenjswanson** [comment]
fixed.
